### ISSUE TITLE
Social links 

### ISSUE THREAD

**Issue by Feinminen** [bimkon/site1#19]
Ссылки на соц сети - надо сделать просто как ссылки на главную страничку (каждой из соцсети). И надо учесть все стандарты для ссылок.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/131249998-84f5eb48-37db-44fb-9e6b-c0c25c675ad9.png)
У меня теперь почему-то нет иконок инсты и твиттера.

**Comment by bimkon** [comment]
Проблема была в том что шрифты material не подключились, поэтому иконок не было видно
